server: 
  port: 8001 #服务端口

spring: 
  application: 
    name: cloud-payment-service #服务名
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

  devtools: 
    restart: 
      enabled: true #是否支持热部署

mybatis: 
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luojia.springcloud.entities  #所有entity别名所在包