server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          # 需要注意的是uri的协议lb,表示启用Gateway的负载均衡功能.
          uri: lb://cloud-payment-service  # 匹配后提供服务的地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由
            #- After=2020-03-21T22:16:00.302+08:00[Asia/Shanghai] # 在指定日期之后配置才生效
            #- Before=2020-03-21T22:22:00.302+08:00[Asia/Shanghai] # 在指定日期之前配置才生效
            #- Between=2020-03-21T22:16:00.302+08:00[Asia/Shanghai], 2020-03-21T22:26:00.302+08:00[Asia/Shanghai]
#            - Cookie=username,luojia
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.luojia.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
          #uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/