server: 
  port: 7002
eureka: 
  instance: 
    hostname: eureka7002.com     # eureka服务端的实力名称
  client: 
    fetch-registry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   # false表示自己不需要向注册中心注册自己
    service-url: 
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/